provider:
  name: faas
  gateway: http://localhost:8080

functions:
  inception:
    lang: dockerfile
    handler: ./function
    image: albertomarini/inception:2.1

spec:
  nodeSelector:
   type: cloud2
